version: "3.9"

services:
  devopsdb:
    image: vinaikumarp/db-app:1.0
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: vinaikumarp/java-app:1.0
    ports:
      - "1113:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
